name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        mongodb-version: [6.0]
    container:
      image: crystallang/crystal:latest
      options: --user root
    steps:
      - name: Install MongoDB
        run: |
          apt update
          apt install sudo
          sudo apt install -y wget gnupg2
          sudo apt install -y mongodb-org
          sudo systemctl enable --now mongod
      - name: Download source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Run tests
        run: crystal spec
