name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        mongodb-version: [7.0, 6.0, 5.0, 4.4]
    container:
      image: crystallang/crystal:latest
      options: --user root
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Start MongoDB
        uses: ankane/setup-mongodb@v1
        uses: ./.
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run tests
        run: crystal spec
