name: Specs

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          # will assign a random free host port
          - 27017/tcp

    container:
      image: crystallang/crystal:latest
      options: --user root

    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Download source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
        env:
          MONGODB_HOST: localhost
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
      - name: Check formatting
        run: crystal tool format --check
      - name: Run tests
        run: crystal spec
