name: Specs

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        mongodb-version: [7.0, 6.0]

    container:
      image: crystallang/crystal:latest
      options: --user root

    steps:
      - name: Install sudo, wget, gnupg2 and systemctl
        run: |
          apt update
          apt install -y sudo
          sudo apt install -y wget gnupg2
          sudo apt -y install systemctl
          sudo apt -y install libturbojpeg0-dev
          sudo wget --no-check-certificate 'http://ftp.uk.debian.org/debian/pool/main/libs/libspng/libspng0_0.7.3-3_amd64.deb' &&
          sudo dpkg -i 'libspng0_0.7.3-3_amd64.deb'
          sudo wget --no-check-certificate 'http://ftp.uk.debian.org/debian/pool/main/libs/libspng/libspng-dev_0.7.3-3_amd64.deb' &&
          sudo dpkg -i 'libspng-dev_0.7.3-3_amd64.deb'
          sudo apt -y install libwebp-dev
      - name: Download source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Start MongoDB
        uses: kebasyaty/setup-mongodb@v1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run tests
        run: |
          crystal spec --tag global_alias
          crystal spec --tag global_regex
          crystal spec --tag global_settings
          crystal spec --tag global_super_collection
          crystal spec --tag i18n
          crystal spec --tag pluto
          crystal spec --tag validator
          crystal spec --tag fields
          crystal spec --tag field_json
          crystal spec --tag model
          crystal spec --tag model_json
          crystal spec --tag mongo_client
          crystal spec --tag migration
          crystal spec --tag check
