name: Specs

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: test
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    container:
      image: crystallang/crystal:latest
      options: --user root

    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Run tests
        run: crystal spec
