name: Specs

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: ["4.4.14", "5.0.9"]

    container:
      image: crystallang/crystal:latest
      options: --user root

    steps:
      - name: Install sudo package
        run: apt update && apt install curl
      - name: Download source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Start MongoDB
        uses: MongoCamp/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: curl http://localhost:27017
      - name: Run tests
        run: crystal spec
