name: Specs

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest
      options: --user root

    services:
      mongodb:
        image: mongo
        ports:
          # will assign a random free host port
          - 27017/tcp

    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Install sudo
        run: apt install sudo
      - name: Run tests
        run: crystal spec
