name: Specs

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        mongodb-version: [7.0, 6.0]

    container:
      image: crystallang/crystal:latest
      options: --user root

    steps:
      - name: Install sudo
        run: |
          apt update
          apt install -y sudo
          sudo apt install -y wget gnupg2
      - name: Download source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Start MongoDB
        uses: kebasyaty/setup-mongodb@v1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run tests
        run: crystal spec
